//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Oct 12 2013 11:45:38).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

// #import "NSObject.h"

@class NSString;

@protocol WCAccountLoginLastUserViewControllerDelegate <NSObject>
- (void)onLastUserChangeAccount;
- (void)onLastUserRegister;
- (void)onForgetPwd;
- (void)onLastUserLoginUserName:(NSString *)arg1 Pwd:(NSString *)arg2;
@end

