//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Oct 12 2013 11:45:38).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

// #import "NSObject.h"

// @class AccountBindPhoneInfo, AuthInfo, 
@class NSArray, NSData, NSDictionary, NSString, UIImage;

@interface WCAccountControlData : NSObject
{
    unsigned long m_uiLoginType;
    unsigned long m_uiFromScene;
    NSString *m_nsEmail;
    NSString *m_nsPwd;
    NSString *m_nsPwdMD5;
    NSString *m_nsUserName;
    NSString *m_nsContryCode;
    NSString *m_nsPhoneNumber;
    NSString *m_nsFormatedPhoneNumber;
    NSString *m_nsTicket;
    int m_iRegisterControlFlag;
    //AuthInfo *m_structAuthInfoWrap;
    NSArray *m_arrNextStep;
    UIImage *m_headImage;
    NSData *m_dtVerifyImg;
    NSString *m_nsAlias;
    NSString *m_nsNickName;
    NSString *m_nsVerifySignature;
    NSString *m_nsVerifyCode;
    int m_iInputType;
    NSArray *m_arrUserName;
    int m_iForceReg;
    int m_iRegMode;
    unsigned long m_uiRegNextShowStyle;
    unsigned long m_uiReportStatus;
    NSDictionary *m_dicStyleKeyValue;
    unsigned long m_uiNextAuthType;
    //AccountBindPhoneInfo *m_oBindPhoneInfo;
}

// @property(retain, nonatomic) AccountBindPhoneInfo *m_oBindPhoneInfo; // @synthesize m_oBindPhoneInfo;
@property(nonatomic) unsigned long m_uiNextAuthType; // @synthesize m_uiNextAuthType;
@property(retain, nonatomic) NSDictionary *m_dicStyleKeyValue; // @synthesize m_dicStyleKeyValue;
@property(nonatomic) unsigned long m_uiReportStatus; // @synthesize m_uiReportStatus;
@property(nonatomic) unsigned long m_uiRegNextShowStyle; // @synthesize m_uiRegNextShowStyle;
@property(nonatomic) int m_iRegMode; // @synthesize m_iRegMode;
@property(nonatomic) int m_iForceReg; // @synthesize m_iForceReg;
@property(retain, nonatomic) NSArray *m_arrUserName; // @synthesize m_arrUserName;
@property(nonatomic) int m_iInputType; // @synthesize m_iInputType;
@property(retain, nonatomic) NSString *m_nsVerifyCode; // @synthesize m_nsVerifyCode;
@property(retain, nonatomic) NSString *m_nsVerifySignature; // @synthesize m_nsVerifySignature;
@property(retain, nonatomic) NSString *m_nsNickName; // @synthesize m_nsNickName;
@property(retain, nonatomic) NSString *m_nsAlias; // @synthesize m_nsAlias;
@property(retain, nonatomic) NSData *m_dtVerifyImg; // @synthesize m_dtVerifyImg;
@property(retain, nonatomic) UIImage *m_headImage; // @synthesize m_headImage;
@property(retain, nonatomic) NSArray *m_arrNextStep; // @synthesize m_arrNextStep;
// @property(retain, nonatomic) AuthInfo *m_structAuthInfoWrap; // @synthesize m_structAuthInfoWrap;
@property(nonatomic) int m_iRegisterControlFlag; // @synthesize m_iRegisterControlFlag;
@property(retain, nonatomic) NSString *m_nsTicket; // @synthesize m_nsTicket;
@property(retain, nonatomic) NSString *m_nsFormatedPhoneNumber; // @synthesize m_nsFormatedPhoneNumber;
@property(retain, nonatomic) NSString *m_nsPhoneNumber; // @synthesize m_nsPhoneNumber;
@property(retain, nonatomic) NSString *m_nsContryCode; // @synthesize m_nsContryCode;
@property(retain, nonatomic) NSString *m_nsUserName; // @synthesize m_nsUserName;
@property(retain, nonatomic) NSString *m_nsPwdMD5; // @synthesize m_nsPwdMD5;
@property(retain, nonatomic) NSString *m_nsPwd; // @synthesize m_nsPwd;
@property(nonatomic) unsigned long m_uiFromScene; // @synthesize m_uiFromScene;
@property(nonatomic) unsigned long m_uiLoginType; // @synthesize m_uiLoginType;
@property(retain, nonatomic) NSString *m_nsEmail; // @synthesize m_nsEmail;
- (void)ParseBindPhoneInfoFromStyle:(id)arg1;
- (BOOL)isFromBindPhone;
- (BOOL)isFromForgetPwd;
- (BOOL)isFromLogin;
- (BOOL)isFromReg;
- (void)dealloc;
- (id)init;

@end

